### ISSUE TITLE
Script compilation failed

### ISSUE THREAD

**Issue by woutercools** [snixtho/tm2020-skids#2]
Skidmarks are displayed ingame but the manager window doesn't open

![image](https://user-images.githubusercontent.com/16439116/167256389-0e93f18b-347f-4257-8025-9df24a3e0d75.png)

**Comment by snixtho** [comment]
I think you wanted to post an issue to this instead: https://github.com/GreepTheSheep/openplanet-skidmarks-manager/

This repository is purely for hosting the skids and explanations of how they work.

**Comment by woutercools** [comment]
indeed, sorry.

Great work with the skid marks styles, btw!
